### ISSUE TITLE
Failed to load external subtitles

### ISSUE THREAD

**Issue by hurgir** [aflextr/turkcealtyazi-stremio-addon#1]
Merhaba, @aflextr  herhangi bir film veya dizi açıp  altyazı seçtiğimde Failed to load external subtitles şeklinde hata veriyor.
![image](https://github.com/aflextr/turkcealtyazi-stremio-addon/assets/104536428/f4916dc6-f0f8-4d55-8e5b-35fc46f906d0)

**Comment by aflextr** [comment]
> Merhaba, @aflextr herhangi bir film veya dizi açıp altyazı seçtiğimde Failed to load external subtitles şeklinde hata veriyor. ![image](https://private-user-images.githubusercontent.com/104536428/310058049-f4916dc6-f0f8-4d55-8e5b-35fc46f906d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MjcwOTksIm5iZiI6MTcwOTcyNjc5OSwicGF0aCI6Ii8xMDQ1MzY0MjgvMzEwMDU4MDQ5LWY0OTE2ZGM2LWYwZjgtNGQ1NS04ZTViLTM1ZmM0NmY5MDZkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxMjA2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDExNjA4MDY4YzRhZjgzMzg5YWE5ZDk1YmJkZmE4ZjY1NjNlZTJhYThlMmE5ZDY3YzhjZDIxZWRiYTc2NjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kgzKbUpqvWbOEx6v6Q6Qw4RjA5HoRGyO9-aDnLlBdjM)

Akşam bir göz atıcam soruna

**Comment by aflextr** [comment]
@hurgir Az önce attığım commit ile sorunun çözülmesi lazım lütfen bakabilir misiniz ?

**Comment by hurgir** [comment]
@aflextr aynı hata devam ediyor, eklenti kaldırıp tekrar yükledim ama sorun çözülmedi.

**Comment by aflextr** [comment]
> @aflextr aynı hata devam ediyor, eklenti kaldırıp tekrar yükledim ama sorun çözülmedi.

![image](https://github.com/aflextr/turkcealtyazi-stremio-addon/assets/53778891/c249eb98-56e8-416c-9b95-f8342b227594)

burada altyazı çıkıyorsa açarken hata veriyorsa başka altyazı seçip tekrar türkçealtyazıyı seçin. ilk seçimde hata verebiliyor. Eğer resimdeki gibi altyazı yoksa filmi ya da diziyi tekrar açmayı deneyin. bunun olmasının sebebi eklentinin proxysine fazla yük binmesinden kaynaklı

**Comment by hurgir** [comment]
altyazı seçeneklerde görünüyör fakat altyazıyı seçtiğimde hata mesajı çıkıyor.

**Comment by aflextr** [comment]
> altyazı seçeneklerde görünüyör fakat altyazıyı seçtiğimde hata mesajı çıkıyor.

açtığın dizi ya da filmin ismini ve bölümünü söyler misin ?

**Comment by hurgir** [comment]
hepsinde aynı ama mesela tt0481369 bunu deneyebilirsin

**Comment by aflextr** [comment]
> hepsinde aynı ama mesela tt0481369 bunu deneyebilirsin

![image](https://github.com/aflextr/turkcealtyazi-stremio-addon/assets/53778891/4f7508b2-3f8c-4bd3-8c22-dc030fd19d50)

bende çalıştı. dediğim gibi  ilk seçtiğin altyazı hata veriyorsa başka seç ve ilk seçtiğin altyazıya tekrar bas. böylece çözülmesi lazım

**Comment by hurgir** [comment]
farklı altyazı seçip tekrar seçme vs farklı tarayıcı hepsini denedim ama sorun devam ediyor

**Comment by hurgir** [comment]
![image](https://github.com/aflextr/turkcealtyazi-stremio-addon/assets/104536428/99b03e78-0cf8-4ab7-94e5-22bf425aed56)

**Comment by aflextr** [comment]
https://github.com/aflextr/turkcealtyazi-stremio-addon/assets/53778891/124695a2-3664-4b18-9245-5c96ad2981e7

Videodaki gösterdiğim gibi olması lazım eğer olmuyorsa hata aldığınız filmin ya da dizinin bölümü varsa atarsanız vaktim olduğunda bir bug fix yayınlayabilirim

**Comment by hurgir** [comment]
İlgin için teşekkürler ama videodaki adımları aynı şekilde hem bu film hem de tt0481369  için uyguladım ama hata veriyor.

**Comment by aflextr** [comment]
> İlgin için teşekkürler ama videodaki adımları aynı şekilde hem bu film hem de tt0481369 için uyguladım ama hata veriyor. Güncelleme: Tv uygulmasında sorun yok sadece web uygulamasında sorun görünüyor

Eğer bilgisayar da kullanıyorsanız arkada stremio uygulamasının açık kalması lazım webin çalışması için

**Comment by hurgir** [comment]
O konuda sorun yok, diğer altyazı eklentileri sıkıntısız çalışıyor

**Comment by aflextr** [comment]
> O konuda sorun yok, diğer altyazı eklentileri sıkıntısız çalışıyor

bir update yayınladım hayla devam ediyor mu sıkıntı ?

**Comment by hurgir** [comment]
> > O konuda sorun yok, diğer altyazı eklentileri sıkıntısız çalışıyor
> 
> bir update yayınladım hayla devam ediyor mu sıkıntı ?

sorun devam ediyor.

**Comment by DarqLord41-del** [comment]
> > > O konuda sorun yok, diğer altyazı eklentileri sıkıntısız çalışıyor
> > 
> > 
> > bir update yayınladım hayla devam ediyor mu sıkıntı ?
> 
> sorun devam ediyor.

Bende Sıkıntısız Çalışıyor.

**Comment by Boradurualp** [comment]
Bu arkadaşın yayınladığı altyazı eklentisinde sorun yoktur. Karakter sorununu dahi çözmüştür.
